config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("jet/", include("jet.urls")),
    path("jet/dashboard/", include("jet.dashboard.urls", "jet-dashboard")),
    path("admin/", admin.site.urls),
    path("", include("ezone.urls")),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ezone/urls.py
from django.urls import path
from . import views as v1
from userprofile import views as v2

urlpatterns = [
    path("", v1.home_view, name="home"),
    path("about/", v1.about_view, name="about"),
    path("search/", v1.search_view, name="search"),
    path("services/", v1.services_view, name="services"),
    path("contact/", v1.contact_view, name="contact"),
    path("products/", v1.products_view, name="products"),
    path("products/create", v1.create_product_view, name="create_product"),
    path("cart/", v1.cart_view, name="cart"),
    path("add-to-cart/<int:product_id>/", v1.add_to_cart, name="add_to_cart"),
    path(
        "change-quantity/<str:product_id>/", v1.change_quantity, name="change_quantity"
    ),
    path(
        "remove-from-cart/<str:product_id>/",
        v1.remove_from_cart,
        name="remove_from_cart",
    ),
    path("checkout/", v1.checkout_view, name="checkout"),
    path("login/", v2.login_view, name="login"),
    path("logout/", v2.logout_view, name="logout"),
    path("signup/", v2.signup_view, name="signup"),
    path("my_store/", v2.my_store_view, name="my_store"),
    path("my_account/", v2.my_account_view, name="my_account"),
    path(
        "my_account/orders/<int:order_id>", v2.my_order_details, name="my_order_details"
    ),
    path(
        "my_account/orders/delete/<int:order_id>", v2.delete_order, name="delete_order"
    ),
    path("my_account/update", v2.update_my_account_view, name="update_my_account"),
    path("not_found/", v1.not_found_view, name="not_found"),
    path(
        "brands/<slug>/",
        v1.brand_details_view,
        name="brand_details",
    ),
    path(
        "categories/<slug>/",
        v1.category_details_view,
        name="category_details",
    ),
    path(
        "<slug:category_slug>/<slug>/",
        v1.product_details_view,
        name="product_details",
    ),
    path(
        "<slug:category_slug>/<slug>/update",
        v1.update_product_view,
        name="update_product",
    ),
    path(
        "<slug:category_slug>/<slug>/delete",
        v1.delete_product_view,
        name="delete_product",
    ),
]

ezone/models.py
from django.contrib.auth.models import User
from django.db import models


class Category(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=50, null=True, blank=True)
    image = models.ImageField(upload_to="categories")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("-created_at",)
        verbose_name_plural = "categories"

    def __str__(self):
        return self.title


class Brand(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=100)
    icon = models.CharField(max_length=50, null=True, blank=True)
    slug = models.SlugField(max_length=100, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Product(models.Model):
    user = models.ForeignKey(
        User, related_name="products", on_delete=models.CASCADE, null=True, blank=True
    )
    title = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, blank=True, null=True)
    image = models.ImageField(upload_to="products")
    description = models.TextField()
    price = models.FloatField()
    category = models.ForeignKey(
        Category, related_name="products", null=True, on_delete=models.SET_NULL
    )
    brand = models.ForeignKey(
        Brand, related_name="products", null=True, on_delete=models.SET_NULL
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ["-created_at"]


class ProductReview(models.Model):
    CHOICES = [("1", "1"), ("2", "2"), ("3", "3"), ("4", "4"), ("5", "5")]
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    review_msg = models.TextField()
    review_rating = models.CharField(choices=CHOICES, max_length=5)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return f"{self.user.username} --- {self.product.title}"


class Order(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    mobile = models.CharField(max_length=255)
    zipcode = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    total_cost = models.IntegerField(default=0)
    is_paid = models.BooleanField(default=False)
    marchant_id = models.CharField(max_length=255)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.IntegerField()
    quantity = models.IntegerField(default=1)

    def total_price(self):
        return float(int(self.product.price) * int(self.quantity))

    def __str__(self):
        return f"{self.quantity} of {self.product.title}"

userprofile/models.py
from django.contrib.auth.models import User
from django.db import models


class Userprofile(models.Model):
    user = models.OneToOneField(
        User, related_name="userprofile", on_delete=models.CASCADE
    )
    first_name = models.CharField(max_length=50, null=True)
    last_name = models.CharField(max_length=50, null=True)
    mobile = models.CharField(max_length=20, null=True)
    date_of_birth = models.DateField(null=True)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username

    def user_fullname(self):
        return f"{self.first_name} {self.last_name}"

userprofile/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm

from ezone.models import Product, Order, ProductReview
from .models import Userprofile


class UserAccountCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")


class UserProfileCreationForm(ModelForm):
    class Meta:
        model = Userprofile
        fields = ("first_name", "last_name", "mobile", "date_of_birth")


class ProductCreationForm(ModelForm):
    class Meta:
        model = Product
        exclude = ["slug", "user"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        formClass = {
            "class": "form-control",
        }
        for field in self.fields:
            self.fields[str(field)].widget.attrs.update(formClass)

        self.fields["image"].widget.attrs.update({"accept": "image/*"})
        self.fields["description"].widget.attrs.update({"rows": "5"})


class ProductUpdateForm(ModelForm):
    class Meta:
        model = Product
        exclude = ["user", "image"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        formClass = {
            "class": "form-control",
        }
        for field in self.fields:
            self.fields[str(field)].widget.attrs.update(formClass)
        self.fields["description"].widget.attrs.update({"rows": "5"})


class OrderCreationForm(ModelForm):
    class Meta:
        model = Order
        fields = (
            "first_name",
            "last_name",
            "mobile",
            "zipcode",
            "address",
            "city",
        )


class ProductReiewCreationForm(ModelForm):
    class Meta:
        model = ProductReview
        fields = ("review_msg", "review_rating")

userprofile/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group, User
from django.shortcuts import render, redirect
from django.contrib import messages

from .forms import UserAccountCreationForm, UserProfileCreationForm
from .decorators import unauthenticated_user
from ezone.models import Product, Order, OrderItem, Category, Brand
from .models import Userprofile


@unauthenticated_user
def login_view(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)

        if user is None:
            messages.info(request, "Invalid Username OR Password!")
            return render(request, "login.html")

        login(request, user)
        return redirect("my_account")
    return render(request, "login.html", {})


def logout_view(request):
    logout(request)
    return redirect("login")


@unauthenticated_user
def signup_view(request):
    form = UserAccountCreationForm()
    if request.method == "POST":
        form = UserAccountCreationForm(request.POST)
        if not form.is_valid():
            messages.info(request, "Please Use valid values!")
            return render(request, "signup.html", {"form": form})

        user = form.save()
        customer_group = Group.objects.get(name="customer")
        user.groups.add(customer_group)
        Userprofile.objects.create(user=user)

        username = form.cleaned_data.get("username")

        messages.success(request, f"Account was created for {username}")
        return redirect("login")
    return render(request, "signup.html", {})


@login_required(login_url="login")
def my_account_view(request):
    context = {
        "form": UserProfileCreationForm(),
        "user": request.user.userprofile,
        "orders": Order.objects.filter(created_by=request.user),
    }

    return render(request, "userprofile.html", context)


@login_required(login_url="login")
def my_order_details(request, order_id):
    order = Order.objects.get(pk=order_id)
    if not order.created_by == request.user:
        messages.info(request, "unauthorized User")
        return redirect("my_account")

    orderItems = OrderItem.objects.filter(order=order)
    context = {"order": order, "orderItems": orderItems}

    return render(request, "order-details.html", context)


@login_required(login_url="login")
def delete_order(request, order_id):
    order = Order.objects.get(pk=order_id)
    if request.method == "POST":
        messages.success(request, f"Order '0{order_id}' Succesfully Deleted")
        order.delete()

    return redirect("my_account")


@login_required(login_url="login")
def update_my_account_view(request):
    form = UserProfileCreationForm()
    if request.method == "POST":
        form = UserProfileCreationForm(request.POST)
        if not form.is_valid():
            messages.info(request, "Account Info Update Failed")
            return render(
                request,
                "userprofile.html",
                {"form": form, "user": request.user.userprofile},
            )

        userprofile = Userprofile.objects.get(id=request.user.id)

        if userprofile:
            userprofile.first_name = form.cleaned_data["first_name"]
            userprofile.last_name = form.cleaned_data["last_name"]
            userprofile.date_of_birth = form.cleaned_data["date_of_birth"]
            userprofile.mobile = form.cleaned_data["mobile"]

            messages.success(request, "Account was updated Successfully")

            userprofile.save()
    return redirect("my_account")


@login_required(login_url="login")
def my_store_view(request):
    if not User.objects.filter(pk=request.user.id, groups__name="staff").exists():
        messages.info(request, "Only authorized personel allowed!")
        return redirect("my_account")

    context = {
        "products": Product.objects.filter(user=request.user),
        "isFirstAdmin": False,
        "users": None,
        "categories": None,
        "brands": None,
    }
    if request.user.id == 1 or "1":
        context["isFirstAdmin"] = True
        context["users"] = User.objects.all().exclude(id=request.user.id)
        context["categories"] = Category.objects.all()
        context["brands"] = Brand.objects.all()

    return render(request, "my_store.html", context)

templates/brand-details.html
{% extends 'layout.html' %}
{% load static %}
{% block page_title %}{{brand.title}} Brand{% endblock page_title %}

{% block main_page_content %}
   <section class="page-title centred">
      <div class="pattern-layer"	style="background-image: url({% static 'images/background/page-title.jpg' %})"></div>
      <div class="auto-container">
         <div class="content-box">
            <h1>{{brand.title}}  Brand</h1>
            <ul class="bread-crumb clearfix">
            <li>
               <i class="icon-home"></i><a href="{% url 'home' %}">Home</a>
            </li>
            <li>brands</li>
            </ul>
         </div>
      </div>
   </section>
   <div class="auto-container" style="margin-top: 50px;margin-bottom:50px">
      {% if products|length <= 0 %}
         <h1 class="centred">No Products for the <span style="color:#d35d09">{{brand.title}}</span> brand Sofar</h1>
      {% else %}
         <div class="items-container row clearfix">
            {% for product in products %}
               <div class="col-lg-3 col-md-6 col-sm-12 shop-block masonry-item small-column best_seller new_arraivals top_rate">
                  <div class="shop-block-one">
                     <div class="inner-box">
                     <figure class="image-box">
                        <img src="{{ product.image.url }}" alt="" />
                        <ul class="info-list clearfix">
                           <li>
                              <a>
                                 <i class="flaticon-heart"></i>
                              </a>
                           </li>
                           <li><a href="/">Add to cart</a></li>
                           <li>
                              <a href="{{ product.image.url }}" class="lightbox-image" data-fancybox="gallery">
                                 <i class="flaticon-search"></i>
                              </a>
                           </li>
                        </ul>
                     </figure>
                     <div class="lower-content">
                        <a class="line-clamp" href="{% url 'product_details' product.category.slug product.slug %}">{{product.title}}</a>
                        <span class="price">${{product.price}}</span>
                     </div>
                     </div>
                  </div>
               </div>
            {% endfor %}
         </div>
      {% endif %}
   </div>
{% endblock main_page_content %}

templates/category-details.html
{% extends 'layout.html' %}
{% load static %}
{% block page_title %}{{category.title}}{% endblock page_title %}

{% block main_page_content %}
   <section class="page-title centred">
      <div class="pattern-layer"	style="background-image: url({% static 'images/background/page-title.jpg' %})"></div>
      <div class="auto-container">
         <div class="content-box">
            <h1>{{category.title}} Category</h1>
            <ul class="bread-crumb clearfix">
            <li>
               <i class="icon-home"></i><a href="{% url 'home' %}">Home</a>
            </li>
            <li>categories</li>
            </ul>
         </div>
      </div>
   </section>
   <div class="auto-container" style="margin-top: 50px;margin-bottom:50px">
      {% if products|length <= 0 %}
         <h1 class="centred">No Products for the <span style="color:#d35d09">{{category.title}}</span> category Sofar</h1>
      {% else %}
         <div class="items-container row clearfix">
            {% for product in products %}
               <div class="col-lg-3 col-md-6 col-sm-12 shop-block masonry-item small-column best_seller new_arraivals top_rate">
                  <div class="shop-block-one">
                     <div class="inner-box">
                     <figure class="image-box">
                        <img src="{{ product.image.url }}" alt="" />
                        <ul class="info-list clearfix">
                           <li>
                              <a>
                                 <i class="flaticon-heart"></i>
                              </a>
                           </li>
                           <li><a href="/">Add to cart</a></li>
                           <li>
                              <a href="{{ product.image.url }}" class="lightbox-image" data-fancybox="gallery">
                                 <i class="flaticon-search"></i>
                              </a>
                           </li>
                        </ul>
                     </figure>
                     <div class="lower-content">
                        <a class="line-clamp" href="{% url 'product_details' product.category.slug product.slug %}">{{product.title}}</a>
                        <span class="price">${{product.price}}</span>
                     </div>
                     </div>
                  </div>
               </div>
            {% endfor %}
         </div>
      {% endif %}
   </div>
{% endblock main_page_content %}

templates/checkout.html
{% extends 'layout.html' %}
{% load static %}
{% block page_title %}Checkout{% endblock page_title %}

{% block main_page_content %}
   <section class="page-title centred">
      <div class="pattern-layer"	style="background-image: url({% static 'images/background/page-title.jpg' %})"></div>
      <div class="auto-container">
         <div class="content-box">
            <h1>Checkout</h1>
            <ul class="bread-crumb clearfix">
            <li>
               <i class="icon-home"></i><a href="{% url 'home' %}">Home</a>
            </li>
            <li>Checkout</li>
            </ul>
         </div>
      </div>
   </section>

   <section class="checkout-section">
      <div class="container">
         {{errors}}
         <div class="row">
            <div class="col-lg-6 col-md-12 col-sm-12 left-column">
               <div class="inner-box">
               <div class="billing-info">
                  <h4 class="sub-title">Billing Details</h4>
                  <form action="{% url 'checkout' %}" method="post" class="billing-form">
                     {% csrf_token %}
                     <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-12 form-group">
                           <label for="id_firstname">First Name*</label>
                           <div class="field-input">
                              <input id="id_firstname" type="text" name="first_name" value="{{user.first_name}}" />
                           </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-12 form-group">
                           <label for="id_lastname">Last Name*</label>
                           <div class="field-input">
                              <input id="id_lastname" type="text" name="last_name" value="{{user.last_name}}" />
                           </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-12 form-group">
                           <label for="id_mobile">Phone Number*</label>
                           <div class="field-input">
                              <input id="id_mobile" type="text" name="mobile" value="{{user.mobile}}" />
                           </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-12 form-group">
                           <label for="id_zipcode">Zip Code*</label>
                           <div class="field-input">
                              <input id="id_zipcode" type="text" name="zipcode" />
                           </div>
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12 form-group">
                           <label for="id_address">Address*</label>
                           <div class="field-input">
                              <input id="id_address" type="text" name="address" class="address" />
                           </div>
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12 form-group">
                           <label for="id_city">Town/City*</label>
                           <div class="field-input">
                              <input id="id_city" type="text" name="city" />
                           </div>
                        </div>
                     </div>
                     <div class="btn-box" style="margin-top: 30px">
                        <button type="submit" class="theme-btn-two">
                           Place Your Order<i class="flaticon-right-1"></i>
                        </button>
                     </div>
                  </form>
               </div>
               </div>
            </div>
            <div class="col-lg-6 col-md-12 col-sm-12 right-column">
               <div class="inner-box">
               <div class="order-info">
                  <h4 class="sub-title">Your Order</h4>
                  <div class="order-product">
                     <ul class="order-list clearfix">
                        <li class="title clearfix">
                           <p>Product</p>
                           <span>Total</span>
                        </li>
                        {% for item in cart %}
                           <li>
                              <div class="single-box clearfix">
                                 <img src="{{item.product.image.url}}" alt="" />
                                 <h6 class="line-clamp">{{item.product.title}}</h6>
                                 <span>${{item.product.price}}</span>
                              </div>
                           </li>
                        {% endfor %}
                        <li class="order-total clearfix">
                           <h6>Order Total</h6>
                           <span>${{cart.get_total_cost}}</span>
                        </li>
                     </ul>
                  </div>
               </div>
               {% comment %} <div class="payment-info">
                  <h4 class="sub-title">Payment Proccess</h4>
                  <div class="payment-inner">
                     <div class="option-block">
                     <div class="custom-controls-stacked">
                        <label class="custom-control material-checkbox">
                           <input
                           type="checkbox"
                           class="material-control-input"
                           />
                           <span class="material-control-indicator"></span>
                           <span class="description">Direct bank transfer</span>
                        </label>
                     </div>
                     <p>
                        Please send a check to Store Name, Store Street, Store
                        Town, Store State / County, Store Postcode.
                     </p>
                     </div>
                     <div class="option-block">
                     <div class="custom-controls-stacked">
                        <label class="custom-control material-checkbox">
                           <input
                           type="checkbox"
                           class="material-control-input"
                           />
                           <span class="material-control-indicator"></span>
                           <span class="description"
                           >Paypal<a href="{% url 'checkout' %}"
                              >What is paypal?</a
                           ></span
                           >
                        </label>
                     </div>
                     </div>
                  </div>
               </div> {% endcomment %}
               </div>
            </div>
         </div>
      </div>
   </section>
{% endblock main_page_content %}

templates/contact.html
{% extends 'layout.html' %}
{% load static %}
{% block page_title %}Contact{% endblock page_title %}

{% block main_page_content %}
   <section class="page-title centred">
      <div class="pattern-layer"	style="background-image: url({% static 'images/background/page-title.jpg' %})"></div>
      <div class="auto-container">
         <div class="content-box">
            <h1>Our Services</h1>
            <ul class="bread-crumb clearfix">
            <li>
               <i class="icon-home"></i><a href="{% url 'home' %}">Home</a>
            </li>
            <li>Our Services</li>
            </ul>
         </div>
      </div>
   </section>

   <section class="address-section">
      <div class="auto-container">
			<div class="sec-title">
				<h2>Our Addresses</h2>
				<p>Excepteur sint occaecat cupidatat non proident sunt</p>
				<span
				class="separator"
				style="background-image: url({% static 'images/icons/separator-1.png' %})"
				></span>
			</div>
			<div class="row clearfix">
				<div class="col-lg-4 col-md-6 col-sm-12 address-column">
				<div class="single-adderss-block">
					<div class="inner-box">
						<h3>Main Office</h3>
						<ul class="info-list clearfix">
						<li>
							<i class="fas fa-map-marker-alt"></i>
							{{ezone_address.address}}
						</li>
						<li>
							<i class="fas fa-phone"></i>
							<a href="tel:{{ezone_address.mobile}}">{{ezone_address.mobile}}</a>
						</li>
						<li>
							<i class="fas fa-envelope"></i>
							<a href="mailto:{{ezone_address.mail}}">{{ezone_address.mail}}</a>
						</li>
						</ul>
					</div>
				</div>
				</div>
				<div class="col-lg-4 col-md-6 col-sm-12 address-column">
				<div class="single-adderss-block">
					<div class="inner-box">
						<h3>London Office</h3>
						<ul class="info-list clearfix">
						<li>
							<i class="fas fa-map-marker-alt"></i>
							PO Box 16122 Collins Street West Victoria 8007 Landon
						</li>
						<li>
							<i class="fas fa-phone"></i>
							<a href="tel:{{ezone_address.mobile}}">{{ezone_address.mobile}}</a>
						</li>
						<li>
							<i class="fas fa-envelope"></i>
							<a href="mailto:{{ezone_address.mail}}">{{ezone_address.mail}}</a>
						</li>
						</ul>
					</div>
				</div>
				</div>
				<div class="col-lg-4 col-md-6 col-sm-12 address-column">
				<div class="single-adderss-block">
					<div class="inner-box">
						<h3>Netherlands Office</h3>
						<ul class="info-list clearfix">
						<li>
							<i class="fas fa-map-marker-alt"></i>
							PO Box 16122 Collins Street West Victoria 8007 Netherlands
						</li>
						<li>
							<i class="fas fa-phone"></i>
							<a href="tel:{{ezone_address.mobile}}">{{ezone_address.mobile}}</a>
						</li>
						<li>
							<i class="fas fa-envelope"></i>
							<a href="mailto:{{ezone_address.mail}}">{{ezone_address.mail}}</a>
						</li>
						</ul>
					</div>
				</div>
				</div>
			</div>
		</div>
   </section>

   <section class="contact-section">
      <div class="auto-container">
			<div class="col-lg-10 col-md-12 col-sm-12 offset-lg-1 big-column">
				<div class="sec-title">
				<h2>Get In Touch</h2>
				<p>Excepteur sint occaecat cupidatat non proident sunt</p>
				<span
					class="separator"
					style="
						background-image: url({% static 'images/icons/separator-1.png' %});
					"
				></span>
				</div>
				<div class="form-inner">
				<form
					method="post"
					action="{% url 'contact' %}"
					id="contact-form"
					class="default-form"
				>
					<div class="row">
						<div class="col-lg-6 col-md-12 col-sm-12 form-group">
						<input
							type="text"
							name="username"
							placeholder="Name"
							required
						/>
						</div>
						<div class="col-lg-6 col-md-12 col-sm-12 form-group">
						<input
							type="email"
							name="email"
							placeholder="Email"
							required
						/>
						</div>
						<div class="col-lg-6 col-md-12 col-sm-12 form-group">
						<input
							type="text"
							name="subject"
							placeholder="Subject"
							required
						/>
						</div>
						<div class="col-lg-6 col-md-12 col-sm-12 form-group">
						<input
							type="text"
							name="phone"
							placeholder="Phone"
							required
						/>
						</div>
						<div class="col-lg-12 col-md-12 col-sm-12 form-group">
						<textarea name="message" placeholder="Message"></textarea>
						</div>
						<div
						class="col-lg-12 col-md-12 col-sm-12 form-group message-btn centred"
						>
						<button
							type="submit"
							class="theme-btn-two"
							name="submit-form"
						>
							Submit Message<i class="flaticon-right-1"></i>
						</button>
						</div>
					</div>
				</form>
				</div>
			</div>
		</div>
   </section>
{% endblock main_page_content %}

templates/not_found.html
{% extends 'layout.html' %}
{% block page_title %}Not Found{% endblock page_title %}

{% block main_page_content %}
   <section class="error-section centred sec-pad">
      <div class="auto-container">
         <div class="inner-box">
            <h1>404</h1>
            <h2>Oops! Page Not Found!</h2>
            <p>Please go back to <a href="{% url 'home' %}">Back homepage</a></p>
            <div class="btn-box">
            <a href="{% url 'home' %}" class="theme-btn-two"
               >Go Back To Home<i class="flaticon-right-1"></i
            ></a>
            <a href="{% url 'products' %}" class="theme-btn-one"
               >Continue Shopping<i class="flaticon-right-1"></i
            ></a>
            </div>
         </div>
      </div>
   </section>
{% endblock main_page_content %}